development:
  clients:
    default:
      uri: mongodb://localhost/govuk_needs_development
      options:
        write:
          w: 1
        read:
          mode: :primary
test:
  clients:
    default:
      uri: mongodb://localhost/govuk_needs_test
      options:
        write:
          w: 1
        read:
          mode: :primary
        max_retries: 1
        retry_interval: 0
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        write:
          w: 1
        read:
          mode: :primary
        retry_interval: 120
